### PR TITLE
Private fields and methods support 

### LINKED ISSUE #702: ERROR: Unexpected character '#' – private class fields
I use in my code `#` for private class fields:

```js
class Main {
    static #foo = "FOO";

    static foo() {
        return Main.#foo;
    }

    #bar;
    constructor(bar = "bar") {
        this.#bar = bar;
    }

    get() {
        return Main.#foo + this.#bar;
    }
}

console.log(Main.foo());
console.log(new Main().get());
```

I use `terser --compress --mangle -o ./dist/main.min.js ./src/main.js` to minify it, but I get:
```
Parse error at ./src/main.js:2,11
    static #foo = "FOO";
           ^
ERROR: Unexpected character '#'
    at js_error (...\node_modules\terser\lib\parse.js:369:11)
    at parse_error (...\node_modules\terser\lib\parse.js:502:9)
    at Object.input (...\node_modules\terser\lib\parse.js:902:9)
    ...
```

Any good workaround? I don't want to remove `#` from my code and from the minified version too.

_Terser 4.6.13_

Although currently only [Chromuim](https://caniuse.com/#search=Private%20class%20fields) and Node.js support this I would prefer to have ability to minimaze the code without any change for them, and with Babel for the others.

### PR DESCRIPTION
**Pull request by rricard**
This PR fixes #702.

### CODE REVIEW

File: lib/output.js [hunk 1]
```diff
@@ -2047,10 +2077,21 @@ function OutputStream(options) {
...
+    });
+    DEFPRINT(AST_PrivateMethod, function(self, output) {
+        var type;
+        if (self.is_generator && self.async) {
+            type = "async*";
+        } else if (self.is_generator) {
+            type = "*";
+        } else if (self.async) {
+            type = "async";
+        }
```
Comment (L2jLiga) [inline lib/output.js:2093]: may be it would be better to write this way?

```suggestion
        var type = '';
        if (self.async) {
            type += "async";
        }
        if (self.is_generator) {
            type += "*";
        }
```

**Review by L2jLiga — APPROVED** [review]
Looks promising!

File: lib/output.js (hunk 1 above)
Comment (rricard) [reply lib/output.js:2093]: This is taken from an exisitng similar node type: if we change the logic here we should change both; now I'm doing a drive by fix which is not ideal...

**Review by dragomirtitian — APPROVED** [review]

**Comment by rricard** [comment]
Hi @fabiosantoscode I just wanted to know when you can review this pr. Feel free to let me know what I can do to push this forward or anything that I can do to make the review easier. Thank you!

**Comment by fabiosantoscode** [comment]
Hey there! I totally missed your updates. This is looking pretty good, and it even has support for private optional properties. I think it's good to merge!

**Comment by rricard** [comment]
Amazing, thank you! No problem, github notifications can be a bit overwhelming sometimes!
